# Start from a base Node.js image
FROM node:14

# Set the working directory in the Docker image
WORKDIR /usr/src/jekomo

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies in the Docker image
RUN npm install

# Copy the rest of the application to the working directory
COPY . .

# Build the application
RUN npm run build

# Expose the port the application runs on
EXPOSE 3000

# Start the application
CMD [ "npm", "run", "start:prod" ]
